package net.atlassian.cmathtutor.domain.persistence.descriptor;

public class IllegalOperationException extends Exception {

    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = 992990681976919280L;

    public IllegalOperationException(String message) {
        super(message);
    }
}
