package net.atlassian.cmathtutor.helper;

import java.util.Properties;

public class VelocityEngineConfig extends Properties {

    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = 2274061539994400318L;

    public VelocityEngineConfig() {
	super();
	put("resource.loaders", "class");
	put("resource.loader.class.class",
		"org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader");
    }

}
